# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f82c54b61615d01bb4c77b117fa2624ea41350c62927ff1605f061fdda6ba5c55f42252e5bacc8837734aec10ad5a1bd50915b9ea51e088a06ea10a35e34c07

test:
  secret_key_base: a3a56180188ec0b7e60b9eed054fde46ff834ebcc0b0bec25d1009bef5b2eb78ef167c2da3dfd71e5fc5b228a86d416324fec0ad5083b3fc6e6614a028cf151e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
